build:
  target: docroot
  build_file: build.make
  options:
    - --no-recursion
subtrees:
  rhymesdistro:
    path: docroot/profiles/rhymesdistro
    uri: 'https://github.com/DrupalLadder/rhymesdistro.git'
    branch: master
    message: 'rhymesdistro subtree from https://github.com/DrupalLadder/rhymesdistro.git'
  rhymes:
    path: docroot/sites/all/modules/rhymesdistro/rhymes
    uri: 'https://github.com/DrupalLadder/rhymes.git'
    branch: master
    message: 'rhymes subtree from https://github.com/DrupalLadder/rhymes.git'
postbuild-commands:
  # Restore symlinks to assets.
  - 'git checkout docroot/sites/default'
  # Remove stuff we don't want.
  - 'rm docroot/.gitignore'
